jobs:
  run_syntax_tests:
    continue-on-error: ${{ matrix.optional }}
    name: Test on ${{ matrix.sublime-channel }} build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Packages
      uses: actions/checkout@v3
      with:
        path: st_syntax_tests/Data/Packages
    - continue-on-error: true
      name: Get binary for ${{ matrix.sublime-channel }} build ${{ matrix.sublime-build
        }}
      run: "if [[ \"${{ matrix.sublime-build }}\" == \"latest\" ]]; then\n  wget -O\
        \ st_syntax_tests.tar.xz https://download.sublimetext.com/latest/dev/linux/x64/syntax_tests\n\
        else\n  wget -O st_syntax_tests.tar.xz https://download.sublimetext.com/st_syntax_tests_build_${{\
        \ matrix.sublime-build }}_x64.tar.xz\nfi\ntar xf st_syntax_tests.tar.xz\n\
        rm st_syntax_tests.tar.xz\n"
    - continue-on-error: true
      name: Run syntax tests
      run: 'cd st_syntax_tests

        ./syntax_tests

        '
    strategy:
      fail-fast: false
      matrix:
        include:
        - optional: true
          sublime-build: 4169
          sublime-channel: stable
        - optional: false
          sublime-build: latest
          sublime-channel: dev
      max-parallel: 2
    timeout-minutes: 15
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
